# Generated by Django 3.2.4 on 2021-07-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(),
        ),
    ]
