# Generated by Django 3.2.4 on 2021-06-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='room',
        ),
    ]
