# Generated by Django 3.2.4 on 2021-06-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_date_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
